version: 2

project_name: rabbithole

before:
  hooks:
    - go mod tidy

builds:
  - id: rabbithole
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - package_name: rabbithole
    builds:
      - rabbithole
    vendor: agustinfitipaldi
    homepage: https://github.com/agustinfitipaldi/rabbithole
    maintainer: Agustin Fitipaldi <agustinfitipaldi@gmail.com>
    description: |
      Linux tool for capturing text selections and routing them through search engines.
      Provides instant access to configurable search engines with sub-50ms response time.
      Features automatic text selection capture, dedicated research windows, and SQLite logging.
    license: MIT
    formats:
      - deb
    dependencies:
      - sxhkd
      - dmenu
      - firefox
      - xsel
      - wmctrl
      - xdotool
      - x11-utils
    contents:
      - src: dist/rabbithole_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/rabbithole
        dst: /usr/local/bin/rabbithole
        file_info:
          mode: 0755